### ISSUE TITLE
Can i use your code for my open source project?

### ISSUE THREAD

**Issue by sofiaschn** [guckstift/shortest-js-snake#3]
Hello!

I'm creating an app that reads games from QR Codes. I saw your code and found it to be perfect for my needs, since it is quite small and runs well, with no dependencies. I published my code in the [project's repo](https://github.com/Matheuschn/game-scanner), along with your code and a QR Code generated from the game's minified source.

I just wanted to know if i can use your code for testing my project. I added a link to your repo in my README.md file, but if you don't agree with me using the code, i can remove it.

Thanks!

**Comment by MohammedAbidNafi** [comment]
You can definitely use it since this project is also open-sourced you can totally use it I guess..

**Comment by guckstift** [comment]
Hi Matheus!
Your project looks interesting. Sure, feel free to use it. Thanks for the acknowledgement! You might even be interested in my hand-minified version. Its only 517 Bytes in size. Maybe strip away the html and dont forget the altered canvas id.

**Comment by sofiaschn** [comment]
Thanks! I will definitely take a look at the minified version.
